### ISSUE TITLE
Regarding the audio backend

### ISSUE THREAD

**Issue by mhd1msyb** [Lyatus/L#2]
Good day,

I have a few questions regarding the audio part of L. Firstly, are 3D environment effects supported (reverb, echo, etc)? Also, I was thinking of potentially utilizing the audio backend in a C++ kit I'm developing on unix. I see there is an `mod/alsa.cpp`, and `src/audio/`, are these all the src/header files required to compile and setup the audio backend on unix? 

Cheers!

**Comment by Lyatus** [comment]
Hello! Sorry about the delay.

Environment effects aren't supported by the core engine itself, the way you'd obtain that currently is to use the `wwise` module or the `fmod` module in your project that both implement `AudioEngine`, you'd then manage all audio effects within Wwise or FMOD and use the tool-agnostic `AudioEngine` singleton to send events to them. Sound/music management (meaning `AudioSourceComponent`) is likely going to be deprecated inside the core engine, it will be replaced by a module that implements `AudioEngine` like `fmod` or `wwise` but in a simple manner (for people who don't want external tools or can be satisfied with simple effects and limited tools).

Regarding your other question, I guess so? If you're willing to output PCM data to alsa then everything should be in `alsa.cpp`, the `src/audio/*` files are more engine related, massaging audio data and things like that.

I hope that answers your questions :)
